config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :courses, only: [:index, :show] do
    resources :teachers, only: [:show], module: :courses do
      resources :ratings, only: [:create], module: :teachers
    end
  end

  namespace :api do
    resources :ratings, only: [:destroy]
  end

  namespace :admin do
    resources :courses
    resources :teachers
  end

  root to: "courses#index"
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_and_belongs_to_many :courses, join_table: :courses_teachers
  has_many :ratings

  GENDERS = %w( Male Female Transgender )

  ransacker :name, formatter: proc {|v| v.downcase } do |parent|
    Arel::Nodes::NamedFunction.new('LOWER',
      [Arel::Nodes::NamedFunction.new('concat_ws', [Arel::Nodes.build_quoted(' '), parent.table[:firstname], parent.table[:lastname]])]
    )
  end

  def name
    [title, firstname, lastname].compact.join(" ")
  end

  def gender
    GENDERS[super || 0]
  end

  def average_rating
    ratings.average(:rating).round
  rescue
    0
  end

  def average_remaining_rating
    5 - average_rating
  end
end

app/controllers/admin/teachers_controller.rb
module Admin
  class TeachersController < AdminController
    before_action :set_teacher, only: [:edit, :update, :destroy]

    def index
      @q = Teacher.ransack(params[:q])
      @teachers = @q.result.order(updated_at: :desc).page params[:page]
    end

    def edit
      render layout: false
    end

    def new
      @teacher = Teacher.new
      render layout: false
    end

    def create
      @teacher = Teacher.new(teacher_params)
      @saved = @teacher.save
    end

    def update
      @teacher.assign_attributes(teacher_params)
      @saved = @teacher.save
    end

    def destroy
      @teacher.destroy

      redirect_to [:admin, :teachers]
    end

    private

    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    def teacher_params
      params.require(:teacher).permit!
    end
  end
end

app/controllers/courses/teachers/ratings_controller.rb
module Courses
  module Teachers
    class RatingsController < MainController
      def create
        @teacher = Teacher.find(params[:teacher_id])
        @teacher.ratings.create(
          comment: params[:comment],
          rating: params[:rating],
          user_id: current_user.id
        )
        @ratings = @teacher.ratings
      end
    end
  end
end

app/controllers/courses/teachers_controller.rb
module Courses
  class TeachersController < MainController
    def show
      @course = Course.find(params[:course_id])
      @teacher = @course.teachers.find(params[:id])
      @ratings = @teacher.ratings

      render layout: false
    end
  end
end

app/views/admin/teachers/_form.html.haml
.modal-dialog.teacher-form
  .modal-content
    .modal-header
      %h5.modal-title
        - if @teacher.persisted?
          = "Update Teacher"
        - else
          = "New Teacher"
      %button.close{"data-dismiss" => "modal", :type => "button"}
        %span ×
    .modal-body
      = simple_form_for [:admin, @teacher], authenticity_token: true, remote: true do |f|
        = f.input :title
        = f.input :firstname
        = f.input :lastname
        = f.input :degree
        = f.input :start_date
        = f.input :school_graduated
        = f.input :major_accomplishments
        = f.submit "Save", class: "d-none"
    .modal-footer
      %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Cancel
      %button.btn.btn-primary.save-teacher{:type => "button"} Save changes

:javascript
  $(function(){
    App.Admin.Teachers.initializeEvents();
  });

app/views/admin/teachers/create.js.erb
var $form = $(".teacher-form").find("form");

<% if @saved %>
  window.location.href = "<%= admin_teachers_path %>";
<% else %>
  $form.renderFormErrors("teacher", <%= @teacher.errors.to_json.html_safe %>)
<% end %>

app/views/admin/teachers/edit.html.haml
= render "form"

app/views/admin/teachers/index.html.haml
= search_form_for @q, url: [:admin, :teachers], class: "form-inline mt-2 mt-md-0 mr-2" do |f|
  = link_to_modal "New Teacher", [:new, :admin, :teacher], class: "btn btn-outline-success mr-auto mr-2"
  = f.text_field :name_or_degree_or_school_graduated_cont, class: "form-control mr-sm-2", placeholder: "Search Instructor..."
%hr

- if @teachers.any?
  %table.table
    %thead.thead-dark
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} Name
        %th{:scope => "col"} Degree
        %th{:scope => "col"} School Graduated
        %th{:scope => "col"}
    %tbody
      - @teachers.each do |teacher|
        %tr
          %th{:scope => "row"}= "C#{teacher.id}"
          %td= teacher.name
          %td= teacher.degree
          %td= teacher.school_graduated
          %td
            .btn-group
              = link_to_modal "Edit", [:edit, :admin, teacher], class: "btn btn-outline-secondary btn-sm br-0"
              = link_to "Delete", "/admin/teachers/#{teacher.id}", class: "btn btn-outline-secondary btn-sm bl-0", method: :delete, data: { confirm: "Are you sure?" }

  = paginate @teachers
- else
  %p.text-muted No results found.

app/views/admin/teachers/new.html.haml
= render "form"

app/views/admin/teachers/update.js.erb
var $form = $(".teacher-form").find("form");

<% if @saved %>
  window.location.href = "<%= admin_teachers_path %>";
<% else %>
  $form.renderFormErrors("teacher", <%= @teacher.errors.to_json.html_safe %>)
<% end %>