config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :courses, only: [:index, :show] do
    resources :teachers, only: [:show], module: :courses do
      resources :ratings, only: [:create], module: :teachers
    end
  end

  namespace :api do
    resources :ratings, only: [:destroy]
  end

  namespace :admin do
    resources :courses
    resources :teachers
  end

  root to: "courses#index"
end

app/controllers/admin/courses_controller.rb
module Admin
  class CoursesController < AdminController
    before_action :set_course, only: [:edit, :update, :destroy]
    before_action :set_teachers, only: [:edit, :new]

    def index
      @q = Course.ransack(params[:q])
      @courses = @q.result.order(updated_at: :desc).page params[:page]
    end

    def edit
      render layout: false
    end

    def new
      @course = Course.new
      render layout: false
    end

    def create
      @course = Course.new(course_params)
      @saved = @course.save
      @course.teacher_ids = params[:course][:teachers_ids]
    end

    def update
      @course.assign_attributes(course_params)
      @saved = @course.save
      @course.teacher_ids = params[:course][:teachers_ids]
    end

    def destroy
      @course.destroy

      redirect_to [:admin, :courses]
    end

    private

    def set_course
      @course = Course.find(params[:id])
    end

    def set_teachers
      @teachers = Teacher.all.order(:firstname)
      @course_teachers = @course.try(:teachers) || Teacher.none
    end

    def course_params
      params.require(:course).permit(:name, :summary, :description, :room)
    end
  end
end

app/controllers/courses/teachers/ratings_controller.rb
module Courses
  module Teachers
    class RatingsController < MainController
      def create
        @teacher = Teacher.find(params[:teacher_id])
        @teacher.ratings.create(
          comment: params[:comment],
          rating: params[:rating],
          user_id: current_user.id
        )
        @ratings = @teacher.ratings
      end
    end
  end
end

app/controllers/courses/teachers_controller.rb
module Courses
  class TeachersController < MainController
    def show
      @course = Course.find(params[:course_id])
      @teacher = @course.teachers.find(params[:id])
      @ratings = @teacher.ratings

      render layout: false
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < MainController
  before_action :authenticate_user!

  def index
    @courses = @q.result.order(updated_at: :desc).page params[:page]
  end

  def show
    @course = Course.find(params[:id])
    @ratings = Rating.where(teacher_id: @course.teacher_ids)
  end
end

app/views/admin/courses/_course_form.html.haml
= simple_form_for [:admin, @course], authenticity_token: true, remote: true do |f|
  = f.input :name
  = f.input :summary
  = f.input :description
  = f.input :room
  = label_tag "teachers", "Instructors:"
  .teachers-list
    - @course_teachers.each do |teacher|
      %input{ name: "course[teachers_ids][]", type: "hidden", multiple: true, value: teacher.id }
  - if @course_teachers.blank?
    %p
      %small.text-muted *Please add instructors
  %p.teachers
    - @course_teachers.each do |teacher|
      %span.badge.badge-secondary.ml-2{ data: { "teacher-id": teacher.id, name: teacher.name } }
        = teacher.name
        %span.remove-instructor &times;
  .form-group.row
    .col-md-9
      = select_tag "teachers", options_from_collection_for_select(@teachers, "id", "name", @teachers.first.id), class: "form-control"
    .col-md-3
      %button.btn.btn-success.form-control.add-instructor{ type: "button" } Add
  = f.submit "Save", class: "d-none"

app/views/admin/courses/_form.html.haml
.modal-dialog.course-form
  .modal-content
    .modal-header
      %h5.modal-title
        - if @course.persisted?
          = "Update Course"
        - else
          = "New Course"
      %button.close{"data-dismiss" => "modal", :type => "button"}
        %span ×
    .modal-body
      = render "course_form"
    .modal-footer
      %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Cancel
      %button.btn.btn-primary.save-course{:type => "button"} Save changes

:javascript
  $(function(){
    App.Admin.Courses.initializeEvents();
  });

app/views/admin/courses/create.js.erb
var $form = $(".course-form").find("form");

<% if @saved %>
  window.location.href = "<%= admin_courses_path %>";
<% else %>
  $form.renderFormErrors("course", <%= @course.errors.to_json.html_safe %>)
<% end %>

app/views/admin/courses/index.html.haml
= search_form_for @q, url: [:admin, :courses], class: "form-inline mt-2 mt-md-0 mr-2" do |f|
  = link_to_modal "New Course", [:new, :admin, :course], class: "btn btn-outline-success mr-auto mr-2"
  = f.text_field :name_or_summary_or_room_cont, class: "form-control mr-sm-2", placeholder: "Search Class..."
%hr

- if @courses.any?
  %table.table
    %thead.thead-dark
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} Class Name
        %th{:scope => "col"} Summary
        %th{:scope => "col"} Room
        %th{:scope => "col"}
    %tbody
      - @courses.each do |course|
        %tr
          %th{:scope => "row"}= "C#{course.id}"
          %td= course.name
          %td= course.summary
          %td= course.room
          %td
            .btn-group
              = link_to_modal "Edit", [:edit, :admin, course], class: "btn btn-outline-secondary btn-sm br-0"
              = link_to "Delete", "/admin/courses/#{course.id}", class: "btn btn-outline-secondary btn-sm bl-0", method: :delete, data: { confirm: "Are you sure?" }

  = paginate @courses
- else
  %p.text-muted No results found.

app/views/admin/courses/update.js.erb
var $form = $(".course-form").find("form");

var data = $form.serializeArray().reduce(function(map, item){
  map[item.name] = item.value;
  return map;
});

<% if @saved %>
  window.location.href = "<%= admin_courses_path %>"
<% else %>
  $form.renderFormErrors("course", <%= @course.errors.to_json.html_safe %>)
<% end %>